apiVersion: v1
kind: PersistentVolume
metadata:
  name: radius-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 64Mi
  hostPath:
    path: /var/hostpath_pv/radius
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radius-pvclaim
  namespace: security-t-pga
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  volumeMode: Filesystem
  volumeName: radius-pv
