apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radius
  name: radius-deployment
  namespace: security-t-pga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius
  template:
    metadata:
      labels:
        app: radius
    spec:
      containers:
      - name: radius
        image: freeradius/freeradius-server:3.0.23
        ports:
        - name: "radius-auth"
          containerPort: 1812
          protocol: UDP
        - name: "radius-acct"
          containerPort: 1813
          protocol: UDP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: 
            add: 
            - NET_BIND_SERVICE
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsUser: 0
          seLinuxOptions: {}
        volumeMounts:
        - mountPath: /etc/raddb
          name: radius-persist
      volumes:
      - name: radius-persist
        persistentVolumeClaim:
          claimName: radius-pvclaim
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: radius-service
  namespace: security-t-pga
spec:
  type: ClusterIP
  clusterIP: "10.6.128.7"
  externalName: "radius.t.pga"
  ports:
  - name: "auth"
    port: 1812
    protocol: UDP
    targetPort: "radius-auth"
  - name: "accounting"
    port: 1813
    protocol: UDP
    targetPort: "radius-acct"
  selector:
    app: radius
status:
  loadBalancer: {}
