apiVersion: v1
kind: PersistentVolume
metadata:
  name: powerdns-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mi
  hostPath:
    path: /var/hostpath_pv/pdns/pdns_mariadb
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-pvc
  namespace: security-t-pga
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  volumeName: powerdns-pv
