apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi    
  hostPath:
    path: /var/hostpath_pv/unifi
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pv-claim
  namespace: security-t-pga
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
